name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    
env:
  BUILD_NUMBER: 0.0.${{github.run_number}}${{ github.ref != 'refs/heads/main' && '-pre' || '' }}
  
jobs:

  build-docker-image:
    name: "Build docker image"
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build the Docker image
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          tags: 
            mattrichardson/afl-dakboard:${{env.BUILD_NUMBER}}
          push: true
          
  create-octopus-release:
    name: "Create Octopus release"
    runs-on: ubuntu-latest
    needs: [build-docker-image]
    env:
      OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_APIKEY  }}
      OCTOPUS_URL: ${{ secrets.OCTOPUS_SERVER }}
      OCTOPUS_SPACE: 'Default'
    steps:
      - name: Create a release in Octopus Deploy 🐙
        uses: OctopusDeploy/create-release-action@v3
        with:
          project: 'afl-dakboard'
          release_number: ${{env.BUILD_NUMBER}}
          package_version: ${{env.BUILD_NUMBER}}
          git_ref: 'main'
