name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    
env:
  BUILD_NUMBER: 0.0.${{github.run_number}}${{ github.ref != 'refs/heads/main' && '-pre' || '' }}
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the Docker image
        uses: docker/build-push-action@v2.6.1
        with:
          file: Dockerfile
          tags: 
            mattrichardson/afl-dakboard:${{env.BUILD_NUMBER}}
          push: true
  create-octopus-release:
    name: "Create Octopus release"
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: "Create a release on Octopus"
        uses: docker://octopusdeploy/octo
        env:
          OCTOPUS_CLI_SERVER: ${{ secrets.OCTOPUS_SERVER }}
          OCTOPUS_CLI_API_KEY: ${{ secrets.OCTOPUS_APIKEY }}
        with:
          args: create-release --project=afl-dakboard --version=${{env.BUILD_NUMBER}} --packageVersion=${{env.BUILD_NUMBER}}
